version: '3.11'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn tldtest.wsgi:application -b 0.0.0.0:8000 --timeout 600
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env.prod.db
volumes:
  postgres_data:
