version: '3.11'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn tldtest.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
