version: '3.11'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn tldtest.wsgi:application --bind 0.0.0.0:8000 --timeout 600
    ports:
      - 8000:8000
